# -*- mode:conf-toml; -*-

[startup]
loaders                  = { commands="default", task="default", parser="default"}
location_check           = { make_missing = true }
# default_cmd            = ""
sources   = {tasks=[".tasks",  "~/.config/.templates/doot/py_upload"], code=[]}
sleep     = { task=0.2, subtask=1, batch=1 }
max_steps = 100_000
# default_task = ""

[startup.plugins]
# Allows for defining shorthands
command        = { other-run = "doot.cmds.run_cmd:RunCmd", tasks = "doot.cmds.list_cmd:ListCmd" }
report-line    = {}
reporter       = {}
action         = {}
task           = {}

[shutdown]
notify                   = { say-on-exit = false }

[settings.commands]
# Override sub settings of a command
run  = { tracker = "default", runner = "default", reporter= "default", report-line = []}
list = { hide=[] }

[logging]
# Standard loggers. See LoggerSpec. and 'doot stub -p'
stream  = { level="WARNING", filter=[],                 target="stdout", format="{levelname:<8} : {message}"  }
file    = { level="DEBUG",   filter=["chainguard"],      target="rotate", format="{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})", filename_fmt="doot.log" }
printer = { level="NOTSET", colour=true,                target=["stdout", "rotate"], format="{message}", filename_fmt="doot_printed.log" }

[logging.subprinters]
default       = {level="WARNING", disabled=false}
cmd           = {level="INFO"}
task          = {level="INFO" }
header        = {level="INFO" }
task_header   = {level="INFO"}

[logging.extra]
# See LoggerSpec. can be used to control any logger if you know its name

[[locations]]
src     = "src"
codegen = {loc="{src}/_codegen", cleanable=true}
temp    = {loc=".temp",          cleanable=true}
logs    = "{temp}/logs"
build   = "{temp}/build"
docs    = "docs"
data    = "data"
